blank_issues_enabled: true
contact_links:
  - name: ğŸ“œ weekly-issues
    url: https://github.com/ruanyf/weekly/issues
    about: æ¨èé¡¹ç›®æˆ–æ–‡ç« æ—¶è¯·å…ˆåœ¨issueåˆ—è¡¨æœç´¢ä¸€ä¸‹æ˜¯å¦å·²æœ‰ç›¸å…³çš„issueå¹¶è¢«æ”¶å½•ï¼Œå¦‚æœæ²¡æœ‰ï¼Œè¯·é€‰æ‹©ä¸åŒç±»åˆ«æ¨¡æ¿æäº¤issueã€‚